function [DATA_SPHERICAL_2D, AZ, EL] = ...
    spherical_projection(DATA_CARTESIAN_3D, ...
                         NUM_AZIMUTH_SAMPLES, ...
                         NUM_ELEVATION_SAMPLES, ...
                         NUM_RADIAL_SAMPLES, ...
                         X_CENTER,...
                         Y_CENTER, ...
                         Z_CENTER,...
                         R_MIN)

[DATA_SPHERICAL_3D, AZ, EL] = ...
    cart3_to_sph3(DATA_CARTESIAN_3D,...
                  NUM_AZIMUTH_SAMPLES,...
                  NUM_ELEVATION_SAMPLES,...
                  NUM_RADIAL_SAMPLES,...
                  X_CENTER, ...
                  Y_CENTER, ...
                  Z_CENTER, ...
                  R_MIN);

% This determines the size of the data
DATA_SPHERICAL_2D = sum(DATA_SPHERICAL_3D, 3);

end